### ISSUE TITLE
Latest opam upgrade kills async_js

### ISSUE THREAD

**Issue by yminsky** [janestreet/async_js#2] opened 2018-05-14 18:29 UTC
This failed as part of an upgrade that bumped ppx_sexp_conv from v0.11.0 to v0.11.1.

```
[yminsky@tiamat RWO]$ opam upgrade
The following actions will be performed:
  ↗  upgrade   ppx_sexp_conv              v0.11.0 to v0.11.1 
  ↗  upgrade   ocamlnet                   4.1.5 to 4.1.6     
  ↻  recompile ppx_sexp_value             v0.11.0            [uses ppx_sexp_conv]
  ↻  recompile ppx_sexp_message           v0.11.0            [uses ppx_sexp_conv]
  ↻  recompile ppx_hash                   v0.11.0            [uses ppx_sexp_conv]
  ↻  recompile ppx_custom_printf          v0.11.0            [uses ppx_sexp_conv]
  ↻  recompile ppx_assert                 v0.11.0            [uses ppx_sexp_conv]
  ↻  recompile gapi-ocaml                 0.3.6              [uses ocamlnet]
  ↻  recompile ppx_base                   v0.11.0            [uses ppx_sexp_conv]
  ↻  recompile bin_prot                   v0.11.0            [uses ppx_sexp_conv]
  ↻  recompile ppx_expect                 v0.11.0            [uses ppx_sexp_conv]
  ↻  recompile sexp_pretty                v0.11.0            [uses ppx_base]
  ↻  recompile ppx_bin_prot               v0.11.0            [uses bin_prot]
  ↻  recompile ppx_jane                   v0.11.0            [uses ppx_sexp_message, ppx_base, ppx_assert, etc.]
  ↻  recompile virtual_dom                v0.11.0            [uses ppx_jane]
  ↻  recompile splittable_random          v0.11.0            [uses ppx_jane]
  ↻  recompile core_kernel                v0.11.0            [uses ppx_sexp_conv]
  ↻  recompile textutils_kernel           v0.11.0            [uses core_kernel]
  ↻  recompile splay_tree                 v0.11.0            [uses core_kernel]
  ↻  recompile record_builder             v0.11.0            [uses core_kernel]
  ↻  recompile re2                        v0.11.0            [uses core_kernel]
  ↻  recompile protocol_version_header    v0.11.0            [uses core_kernel]
  ↻  recompile patience_diff              v0.11.0            [uses core_kernel]
  ↻  recompile incremental_kernel         v0.11.0            [uses core_kernel]
  ↻  recompile expect_test_helpers_kernel v0.11.0            [uses core_kernel, sexp_pretty]
  ↻  recompile core                       v0.11.1            [uses ppx_assert]
  ↻  recompile async_kernel               v0.11.0            [uses core_kernel]
  ↻  recompile incr_select                v0.11.0            [uses core_kernel]
  ↻  recompile incr_map                   v0.11.0            [uses core_kernel]
  ↻  recompile textutils                  v0.11.0            [uses textutils_kernel, core, ppx_jane]
  ↻  recompile async_unix                 v0.11.0            [uses core, async_kernel, ppx_jane]
  ↻  recompile async_rpc_kernel           v0.11.0            [uses core_kernel]
  ↻  recompile core_extended              v0.11.0            [uses bin_prot]
  ↻  recompile async_js                   v0.11.0            [uses async_kernel, ppx_jane]
  ↻  recompile async_extra                v0.11.0            [uses core, async_kernel, ppx_jane]
  ↻  recompile core_bench                 v0.11.0            [uses core_extended]
  ↻  recompile incr_dom                   v0.11.0            [uses core_kernel]
  ↻  recompile async                      v0.11.0            [uses core, async_kernel, ppx_jane]
  ↻  recompile incr_dom_widgets           v0.11.0            [uses splay_tree, incremental_kernel, incr_map, etc.]
  ↻  recompile expect_test_helpers        v0.11.0            [uses sexp_pretty]
  ↻  recompile conduit-async              1.1.0              [uses ppx_sexp_conv]
  ↻  recompile async_shell                v0.11.0            [uses core_extended]
  ↻  recompile patdiff                    v0.11.0            [uses core_extended]
  ↻  recompile cohttp-async               1.0.2              [uses conduit-async]
===== ↻  42   ↗  2 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[async.v0.11.0] found in cache
[async_extra.v0.11.0] found in cache
[async_js.v0.11.0] found in cache
[async_kernel.v0.11.0] found in cache
[async_rpc_kernel.v0.11.0] found in cache
[async_shell.v0.11.0] found in cache
[async_unix.v0.11.0] found in cache
[bin_prot.v0.11.0] found in cache
[cohttp-async.1.0.2] found in cache
[conduit-async.1.1.0] found in cache
[core.v0.11.1] found in cache
[core_bench.v0.11.0] found in cache
[core_extended.v0.11.0] found in cache
[core_kernel.v0.11.0] found in cache
[expect_test_helpers.v0.11.0] found in cache
[expect_test_helpers_kernel.v0.11.0] found in cache
[gapi-ocaml.0.3.6] found in cache
[incr_dom.v0.11.0] found in cache
[incr_dom_widgets.v0.11.0] found in cache
[incr_map.v0.11.0] found in cache
[incr_select.v0.11.0] found in cache
[incremental_kernel.v0.11.0] found in cache
[ocamlnet.4.1.6] found in cache
[patdiff.v0.11.0] found in cache
[patience_diff.v0.11.0] found in cache
[ppx_assert.v0.11.0] found in cache
[ppx_base.v0.11.0] found in cache
[ppx_bin_prot.v0.11.0] found in cache
[ppx_custom_printf.v0.11.0] found in cache
[ppx_expect.v0.11.0] found in cache
[ppx_hash.v0.11.0] found in cache
[ppx_jane.v0.11.0] found in cache
[ppx_sexp_conv.v0.11.1] found in cache
[ppx_sexp_message.v0.11.0] found in cache
[ppx_sexp_value.v0.11.0] found in cache
[protocol_version_header.v0.11.0] found in cache
[re2.v0.11.0] found in cache
[record_builder.v0.11.0] found in cache
[sexp_pretty.v0.11.0] found in cache
[splay_tree.v0.11.0] found in cache
[splittable_random.v0.11.0] found in cache
[textutils.v0.11.0] found in cache
[textutils_kernel.v0.11.0] found in cache
[virtual_dom.v0.11.0] found in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
⊘  removed   async_shell.v0.11.0
⊘  removed   cohttp-async.1.0.2
⊘  removed   conduit-async.1.1.0
⊘  removed   core_bench.v0.11.0
⊘  removed   incr_dom_widgets.v0.11.0
⊘  removed   incr_dom.v0.11.0
⊘  removed   async_js.v0.11.0
⊘  removed   incr_map.v0.11.0
⊘  removed   incr_select.v0.11.0
⊘  removed   incremental_kernel.v0.11.0
⊘  removed   patdiff.v0.11.0
⊘  removed   core_extended.v0.11.0
⊘  removed   expect_test_helpers.v0.11.0
⊘  removed   async.v0.11.0
⊘  removed   async_extra.v0.11.0
⊘  removed   async_rpc_kernel.v0.11.0
⊘  removed   async_unix.v0.11.0
⊘  removed   async_kernel.v0.11.0
⊘  removed   expect_test_helpers_kernel.v0.11.0
⊘  removed   patience_diff.v0.11.0
⊘  removed   protocol_version_header.v0.11.0
⊘  removed   re2.v0.11.0
⊘  removed   record_builder.v0.11.0
⊘  removed   sexp_pretty.v0.11.0
⊘  removed   splay_tree.v0.11.0
⊘  removed   textutils.v0.11.0
⊘  removed   core.v0.11.1
⊘  removed   textutils_kernel.v0.11.0
⊘  removed   core_kernel.v0.11.0
⊘  removed   splittable_random.v0.11.0
⊘  removed   virtual_dom.v0.11.0
⊘  removed   ppx_jane.v0.11.0
⊘  removed   ppx_base.v0.11.0
⊘  removed   ppx_bin_prot.v0.11.0
⊘  removed   bin_prot.v0.11.0
⊘  removed   ppx_expect.v0.11.0
⊘  removed   ppx_assert.v0.11.0
⊘  removed   ppx_custom_printf.v0.11.0
⊘  removed   ppx_hash.v0.11.0
⊘  removed   ppx_sexp_message.v0.11.0
⊘  removed   ppx_sexp_value.v0.11.0
⊘  removed   ppx_sexp_conv.v0.11.0
∗  installed ppx_sexp_conv.v0.11.1
∗  installed ppx_hash.v0.11.0
∗  installed ppx_assert.v0.11.0
∗  installed ppx_custom_printf.v0.11.0
∗  installed ppx_sexp_message.v0.11.0
∗  installed ppx_sexp_value.v0.11.0
∗  installed ppx_base.v0.11.0
∗  installed bin_prot.v0.11.0
∗  installed ppx_expect.v0.11.0
∗  installed sexp_pretty.v0.11.0
∗  installed ppx_bin_prot.v0.11.0
∗  installed ppx_jane.v0.11.0
∗  installed splittable_random.v0.11.0
∗  installed virtual_dom.v0.11.0
∗  installed core_kernel.v0.11.0
∗  installed expect_test_helpers_kernel.v0.11.0
∗  installed incremental_kernel.v0.11.0
∗  installed async_kernel.v0.11.0
∗  installed patience_diff.v0.11.0
∗  installed protocol_version_header.v0.11.0
∗  installed incr_map.v0.11.0
∗  installed record_builder.v0.11.0
∗  installed splay_tree.v0.11.0
∗  installed textutils_kernel.v0.11.0
∗  installed incr_select.v0.11.0
∗  installed async_rpc_kernel.v0.11.0
∗  installed core.v0.11.1
[ERROR] The compilation of async_js failed at "/home/yminsky/.opam/fresh-4.06.1/bin/jbuilder build -p async_js -j
        7".
∗  installed textutils.v0.11.0
∗  installed async_unix.v0.11.0
∗  installed async_extra.v0.11.0
∗  installed async.v0.11.0
[ERROR] The compilation of conduit-async failed at "/home/yminsky/.opam/fresh-4.06.1/bin/jbuilder build -p
        conduit-async -j 7".
∗  installed expect_test_helpers.v0.11.0
⊘  removed   gapi-ocaml.0.3.6
⊘  removed   ocamlnet.4.1.5
∗  installed ocamlnet.4.1.6
∗  installed gapi-ocaml.0.3.6
∗  installed re2.v0.11.0
∗  installed core_extended.v0.11.0
∗  installed async_shell.v0.11.0
∗  installed core_bench.v0.11.0
∗  installed patdiff.v0.11.0

#=== ERROR while compiling conduit-async.1.1.0 ================================#
# context      2.0.0~beta6 | linux/x86_64 | ocaml-base-compiler.4.06.1 | https://opam.ocaml.org/2.0#57ab599b
# path         ~/.opam/fresh-4.06.1/.opam-switch/build/conduit-async.1.1.0
# command      ~/.opam/fresh-4.06.1/bin/jbuilder build -p conduit-async -j 7
# exit-code    1
# env-file     ~/.opam/log/conduit-async-5060-a7a712.env
# output-file  ~/.opam/log/conduit-async-5060-a7a712.out
### output ###
#       ocamlc async/.conduit_async.objs/conduit_async.{cmi,cmti} (exit 2)
# (cd _build/default && /home/yminsky/.opam/fresh-4.06.1/bin/ocamlc.opt -w -40 -g -bin-annot -I async/.conduit_async.objs -I /home/yminsky/.opam/fresh-4.06.1/lib/astring -I /home/yminsky/.opam/fresh-4.06.1/lib/async -I /home/yminsky/.opam/fresh-4.06.1/lib/async_extra -I /home/yminsky/.opam/fresh-4.06.1/lib/async_kernel -I /home/yminsky/.opam/fresh-4.06.1/lib/async_rpc_kernel -I /home/yminsky/.o[...]
# File "async/conduit_async.mli", line 1:
# Error: The files /home/yminsky/.opam/fresh-4.06.1/lib/async/async.cmi
#        and /home/yminsky/.opam/fresh-4.06.1/lib/ipaddr/ipaddr.cmi
#        make inconsistent assumptions over interface Ppx_sexp_conv_lib


#=== ERROR while compiling async_js.v0.11.0 ===================================#
# context      2.0.0~beta6 | linux/x86_64 | ocaml-base-compiler.4.06.1 | https://opam.ocaml.org/2.0#57ab599b
# path         ~/.opam/fresh-4.06.1/.opam-switch/build/async_js.v0.11.0
# command      ~/.opam/fresh-4.06.1/bin/jbuilder build -p async_js -j 7
# exit-code    1
# env-file     ~/.opam/log/async_js-5060-129cd0.env
# output-file  ~/.opam/log/async_js-5060-129cd0.out
### output ###
#       ocamlc src/.async_js.objs/async_js__Rpc.{cmi,cmti} (exit 2)
# (cd _build/default && /home/yminsky/.opam/fresh-4.06.1/bin/ocamlc.opt -w -40 -safe-string -g -bin-annot -I src/.async_js.objs -I /home/yminsky/.opam/fresh-4.06.1/lib/async_kernel -I /home/yminsky/.opam/fresh-4.06.1/lib/async_rpc_kernel -I /home/yminsky/.opam/fresh-4.06.1/lib/base -I /home/yminsky/.opam/fresh-4.06.1/lib/base/caml -I /home/yminsky/.opam/fresh-4.06.1/lib/base/md5 -I /home/yminsk[...]
# File "src/rpc.mli", line 1:
# Error: The files /home/yminsky/.opam/fresh-4.06.1/lib/core_kernel/core_kernel.cmi
#        and /home/yminsky/.opam/fresh-4.06.1/lib/uri/uri.cmi
#        make inconsistent assumptions over interface Ppx_sexp_conv_lib



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
┌─ The following actions were aborted
│ ∗  install cohttp-async     1.0.2
│ ∗  install incr_dom         v0.11.0
│ ∗  install incr_dom_widgets v0.11.0
└─ 
┌─ The following actions failed
│ λ  build async_js      v0.11.0
│ λ  build conduit-async 1.1.0
└─ 
┌─ The following changes have been performed
│ ⊘  remove    async_js                   v0.11.0
│ ⊘  remove    cohttp-async               1.0.2
│ ⊘  remove    conduit-async              1.1.0
│ ⊘  remove    incr_dom                   v0.11.0
│ ⊘  remove    incr_dom_widgets           v0.11.0
│ ↻  recompile async                      v0.11.0
│ ↻  recompile async_extra                v0.11.0
│ ↻  recompile async_kernel               v0.11.0
│ ↻  recompile async_rpc_kernel           v0.11.0
│ ↻  recompile async_shell                v0.11.0
│ ↻  recompile async_unix                 v0.11.0
│ ↻  recompile bin_prot                   v0.11.0
│ ↻  recompile core                       v0.11.1
│ ↻  recompile core_bench                 v0.11.0
│ ↻  recompile core_extended              v0.11.0
│ ↻  recompile core_kernel                v0.11.0
│ ↻  recompile expect_test_helpers        v0.11.0
│ ↻  recompile expect_test_helpers_kernel v0.11.0
│ ↻  recompile gapi-ocaml                 0.3.6
│ ↻  recompile incr_map                   v0.11.0
│ ↻  recompile incr_select                v0.11.0
│ ↻  recompile incremental_kernel         v0.11.0
│ ↻  recompile patdiff                    v0.11.0
│ ↻  recompile patience_diff              v0.11.0
│ ↻  recompile ppx_assert                 v0.11.0
│ ↻  recompile ppx_base                   v0.11.0
│ ↻  recompile ppx_bin_prot               v0.11.0
│ ↻  recompile ppx_custom_printf          v0.11.0
│ ↻  recompile ppx_expect                 v0.11.0
│ ↻  recompile ppx_hash                   v0.11.0
│ ↻  recompile ppx_jane                   v0.11.0
│ ↻  recompile ppx_sexp_message           v0.11.0
│ ↻  recompile ppx_sexp_value             v0.11.0
│ ↻  recompile protocol_version_header    v0.11.0
│ ↻  recompile re2                        v0.11.0
│ ↻  recompile record_builder             v0.11.0
│ ↻  recompile sexp_pretty                v0.11.0
│ ↻  recompile splay_tree                 v0.11.0
│ ↻  recompile splittable_random          v0.11.0
│ ↻  recompile textutils                  v0.11.0
│ ↻  recompile textutils_kernel           v0.11.0
│ ↻  recompile virtual_dom                v0.11.0
│ ↗  upgrade   ocamlnet                   4.1.5 to 4.1.6
│ ↗  upgrade   ppx_sexp_conv              v0.11.0 to v0.11.1
└─ 

The former state can be restored with:
    opam switch import "/home/yminsky/.opam/fresh-4.06.1/.opam-switch/backup/state-20180514182102.export"
Or you can retry to install your package selection with:
    opam install --restore
```

**Comment by ghost** [comment] 2018-05-15 08:40
It might be due to `ppx_sexp_conv` being incorrectly marked as a build only dependency by some packages. Reinstalling the switch should fix the issue

**Comment by hhugo** [comment] 2020-05-27 11:36
Unable to reproduce

**Closed as completed by hhugo** 2020-05-27 11:36 UTC
Labels: forwarded-to-js-devs
